services:
  - type: web
    name: rift-ecommerce
    env: php
    phpVersion: "8.1"  # Laravel-friendly version
    repo: https://github.com/SaurokiFestus/rift
    branch: main
    buildCommand: "composer install && npm install && npm run build"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false  # Add manually after
      - key: APP_URL
        value: "https://rift.onrender.com"